// <auto-generated />
using System;
using Delos.Westworld.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Delos.Westworld.Infrastructure.Migrations
{
    [DbContext(typeof(WestworldDbContext))]
    [Migration("20200923130657_HostPictureFieldAdded")]
    partial class HostPictureFieldAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Delos.Westworld.Domain.Host", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CurrentParkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSystemReview")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentParkId");

                    b.ToTable("Hosts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("53205ba8-c39a-4fc9-ab19-79cfe43a5de9"),
                            Biography = "Dolores had a long history of being known as the oldest active host in Westworld[2]. Later, she revealed that she was the first host, and from her, all other hosts are based.[3]",
                            CurrentParkId = new Guid("306db597-a981-4072-b84a-646747387f5d"),
                            DateOfCreation = new DateTime(2020, 8, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            LastSystemReview = new DateTime(2020, 9, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Dolores Abernathy",
                            PictureUrl = "https://vignette.wikia.nocookie.net/westworld/images/b/bc/Westworld-episode-5_Dolores_infobox.jpg/revision/latest/top-crop/width/200/height/150?cb=20161031210817"
                        },
                        new
                        {
                            Id = new Guid("20f75515-cd6b-4635-88c4-03abe4a4ebf8"),
                            Biography = "Some years after Arnold died, Bernard was created by Dr. Robert Ford. Ford programmed Bernard to think of himself as a human.",
                            CurrentParkId = new Guid("306db597-a981-4072-b84a-646747387f5d"),
                            DateOfCreation = new DateTime(2020, 4, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            LastSystemReview = new DateTime(2020, 9, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Bernard Lowe",
                            PictureUrl = "https://vignette.wikia.nocookie.net/westworld/images/4/43/Bernard_Lowe_Season_3.jpg/revision/latest?cb=20200307120558"
                        },
                        new
                        {
                            Id = new Guid("ba2608b9-23c8-4d71-a51c-6c3c9b07dfc6"),
                            Biography = "Clementine was one of the earliest hosts designed by Robert Ford's and Arnold Weber's startup called the Argos Initiative. She was though preceded by at least Dolores Abernathy.",
                            CurrentParkId = new Guid("306db597-a981-4072-b84a-646747387f5d"),
                            DateOfCreation = new DateTime(2020, 8, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            LastSystemReview = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Clementine Pennyfeather",
                            PictureUrl = "https://vignette.wikia.nocookie.net/westworld/images/8/8b/Clementine_Pennyfeather.jpg/revision/latest?cb=20161104230847"
                        },
                        new
                        {
                            Id = new Guid("6868b126-84ff-4d92-9220-fd05a76c140a"),
                            Biography = "Akane was created by Lee Sizemore as a Shōgunworld's counterpart to Maeve Millay. Sizemore claims he felt justified to do so, as he was under stress to create 300 new narratives in 3 weeks.",
                            CurrentParkId = new Guid("b6daf08d-8f42-42a6-ab95-23c7066bd7cf"),
                            DateOfCreation = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            LastSystemReview = new DateTime(2020, 9, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Akane",
                            PictureUrl = "https://vignette.wikia.nocookie.net/westworld/images/f/f3/Akane.jpg/revision/latest/scale-to-width-down/620?cb=20180520132523"
                        },
                        new
                        {
                            Id = new Guid("e734bab8-c0aa-41c7-b01c-a77b3fc20acf"),
                            Biography = "Musashi was created by Lee Sizemore as Shōgunworld's counterpart to Hector Escaton. Sizemore claims he felt justified in copying large parts of Hector's code, as he was under stress to create 300 new narratives in 3 weeks.",
                            CurrentParkId = new Guid("b6daf08d-8f42-42a6-ab95-23c7066bd7cf"),
                            DateOfCreation = new DateTime(2020, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            LastSystemReview = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Musashi",
                            PictureUrl = "https://vignette.wikia.nocookie.net/westworld/images/6/6b/Musashi_Akane_No_Mai.jpg/revision/latest?cb=20180520131337"
                        },
                        new
                        {
                            Id = new Guid("a77d4f82-8045-4b03-9e89-ec595fbfe8c0"),
                            Biography = " Maeve Millay is a main character and a host in Westworld. She is a brothel madam in the local Mariposa Saloon. She is one of the first hosts who appears to question her reality, after a series of flashback events - and an apparently chance encounter with Dolores Abernathy in the street outside the Saloon.",
                            CurrentParkId = new Guid("9ebd3c29-f228-4af0-af1b-2688cc8e387c"),
                            DateOfCreation = new DateTime(2020, 5, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            LastSystemReview = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Maeve Millay",
                            PictureUrl = "https://vignette.wikia.nocookie.net/westworld/images/7/78/Maeves1.jpeg/revision/latest/top-crop/width/200/height/150?cb=20200506155237"
                        },
                        new
                        {
                            Id = new Guid("2f71f976-db4d-4cc4-8bc5-2726d299ef9e"),
                            Biography = " Hector Escaton is a host and Westworld's permanent “Most Wanted” bandit. He is a terrifying and brutal criminal, and has a dark sense of humor to match. He subscribes to the theory that the world is a mad place, and the only way to survive is to embrace the role of predator. He is portrayed by Rodrigo Santoro.",
                            CurrentParkId = new Guid("9ebd3c29-f228-4af0-af1b-2688cc8e387c"),
                            DateOfCreation = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            LastSystemReview = new DateTime(2020, 6, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Hector Escaton",
                            PictureUrl = "https://vignette.wikia.nocookie.net/westworld/images/b/b3/Hector_Escaton_infobox_new.jpg/revision/latest?cb=20161024002853"
                        });
                });

            modelBuilder.Entity("Delos.Westworld.Domain.Park", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("306db597-a981-4072-b84a-646747387f5d"),
                            Description = "Experience the first vacation destination where you can live without limits. Westworld is a meticulously crafted and artfully designed park offering an unparalleled, immersive world where you have the freedom to become who you’ve always wanted to be — or who you never knew you were.",
                            Name = "Westworld"
                        },
                        new
                        {
                            Id = new Guid("b6daf08d-8f42-42a6-ab95-23c7066bd7cf"),
                            Description = "\"Shōgunworld\" is park two at Delos Destinations, intended for those who find Westworld too tame. Based on the Edo period in Japanese history, Shōgunworld is an artfully-curated vacation destination, where guests can experience the full complexity of nature - beauty and danger, good and evil - in a place nestled from the passage of time.",
                            Name = "Shogunworld "
                        },
                        new
                        {
                            Id = new Guid("9ebd3c29-f228-4af0-af1b-2688cc8e387c"),
                            Description = "\"Warworld\" is a simulated world and could possibly be park three at Delos Destinations. This park is based on Italian history during World War II, more specifically when Italy was occupied by Nazi Germany between 1943 and 1945 and made into the Italian Social Republic - popularly and historically known as the Republic of Salò.",
                            Name = "Warworld"
                        },
                        new
                        {
                            Id = new Guid("5cda564c-7f41-429d-b151-ca0aa941a99d"),
                            Description = "\"The Raj\" is park six at Delos Destinations and the first park revealed that doesn't use the \"-world\" suffix in its name. The park is named after and inspired by the \"British Raj\", the period between 1858 and 1947 in which the British Crown ruled over the Indian subcontinent.",
                            Name = "The Raj"
                        });
                });

            modelBuilder.Entity("Delos.Westworld.Domain.Host", b =>
                {
                    b.HasOne("Delos.Westworld.Domain.Park", "CurrentPark")
                        .WithMany("Hosts")
                        .HasForeignKey("CurrentParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
